# 数据源信息
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.11.235:3306/crm_db?serverTimezone=UTC
    username: root
    password: 2727981781

mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 9000